sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tKf7JNVTw6VDJsvAgTN
    access-key-secret: uFqqYU8K3gfWVVcWj9cglaFDQvPp7B
    bucket-name: sky-takeout-xs
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx1b5ac394c8f4c81c
    secret: e773d2927f4d9b9263b003d36aee1e9d

